#!/bin/sh

LED_ON_CMD="mdio-tool w eth0 0x15 0x155"
LED_OFF_CMD="mdio-tool w eth0 0x15 0x044"

function blink() {
    COUNT=${1}
    ON_DURATION=${2}
    OFF_DURATION=${3:-${ON_DURATION}}

    for i in $(seq ${COUNT})
    do
        ${LED_ON_CMD}
        sleep ${ON_DURATION}

        ${LED_OFF_CMD}
        sleep ${OFF_DURATION}
    done
}

trap "${LED_OFF_CMD} ; exit" EXIT INT TERM QUIT HUP

blink 30 0.1 0.4 &